#name: Your New Jekyll Site
#markdown: redcarpet
#pygments: true

# Dependencies
name: Charlie Stockman
markdown:         redcarpet
highlighter:      pygments

# Permalinks
#permalink:        pretty
#relative_permalinks: true

# Setup
title:            Charlie Stockman
tagline:          'Writer.'
description:      'Writer. Performer. Programmer.'
#url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
